name: "sd-mesh-texture-stage2"
tag: "seed${seed}-${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 1024
  height: 1024
  eval_height: 1024
  eval_width: 1024
  camera_distance_range: [1.5, 1.8]
  fovy_range: [60, 70]
  elevation_range: [0, 40]
  eval_camera_distance: 1.8
  eval_fovy_deg: 65.
  n_val_views: 4

  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.

system_type: "prolificdreamer-system"
system:
  stage: texture
  geometry_convert_from: ???
  geometry_convert_inherit_texture: true
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    radius: 1.0 # consistent with last stage
    isosurface_resolution: 128 # consistent with last stage
    isosurface_deformable_grid: true
    isosurface_remove_outliers: true
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 20
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: false

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: cuda

  noise_generator_type: "triplane-noise-generator"
  noise_generator:
    # 0(random)-1(determined)
    sqrt_beta: 1.0
    noise_h: 64
    noise_w: 64
    noise_background_fix: true

    noise_ptc_resolution: 2048
    peel_depth: 32 # just some large number
    separate: false
    apply_transformation: sph2sqr
    context_type: cuda

    smooth_regularization: true
    weight_decay: 0.9999

  t_scheduler_type: timestep-scheduler
  t_scheduler:
    min_step_percent: 0.02
    max_step_percent: 0.98
    sqrt_anneal: false
    dreamtime_anneal: null
    trainer_max_steps: ${trainer.max_steps}
    linear_anneal_max: [0.6, 0.8]
    linear_anneal_min: ${system.t_scheduler.linear_anneal_max}
    linear_anneal_steps: [0, 15_000]

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "lack details, ugly, oversmoothed, bad structure, out of focus, blurry, cartoon, oversaturated, foggy, hazy, ugly, bad anatomy, malformed, pixelated obscure, unnatural colors, dull, unclear, lowres, low quality, deformed, dehydrated"
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "stable-diffusion-unified-guidance"
  guidance:
    weighting_strategy: dmd
    guidance_type: sds
    guidance_stab_type: null
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    guidance_scale: 75.
    guidance_scale_img: 3.
    use_img_loss: gt

  loggers:
    wandb:
      enable: false
      project: ${name}
      name: ${tag}

  loss:
    lambda_sd: 1.
    lambda_sd_img: 1e-2
    lambda_orient: 0.
    lambda_sparsity: 0.
    lambda_opaque: 0.
    lambda_z_variance: 0.

  optimizer:
    name: Adam
    args:
      betas: [0.9, 0.99]
      eps: 1.e-8
    params:
      geometry.encoding:
        lr: 1e-2
      geometry.feature_network:
        lr: 1e-3
      geometry.sdf:
        lr: 1e-4
      geometry.deformation:
        lr: 1e-4
      background:
        lr: 1e-3

trainer:
  max_steps: 15_000
  log_every_n_steps: 50
  num_sanity_val_steps: 0
  val_check_interval: 500
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
