name: "neurlpspp-vsd-tune"
tag: "vsdd-wd${system.noise_generator.weight_decay}-gs${system.guidance.guidance_scale}-limg${system.loss.lambda_sd_img}-sb${system.noise_generator.sqrt_beta}-dt${system.t_scheduler.dreamtime_anneal}-seed${seed}-${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0
#  python launch.py --train --gpu 5 --config configs/prolificdreamer-hifa.yaml system.guidance.guidance_stab_type=vcfd
data_type: "random-camera-datamodule"
data:
  batch_size: [1,1]
  width: [128, 512]
  height: [128, 512]
  resolution_milestones: [5_000]

  camera_distance_range: [1.0, 1.5]
  fovy_range: [40, 70]
  elevation_range: [-10, 45]
  eval_camera_distance: 1.5
  eval_fovy_deg: 65.
  n_val_views: 4

  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.

system_type: "dreamfusion-system"
system:
  enable_eval_metirc: true
  geometry_type: "implicit-volume"
  geometry:
    radius: 1.0
    normal_type: null

    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 5.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 20
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true
 
  renderer_type: "nerf-volume-renderer-with-budget"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512
    train_gradient_budget: 13_000_000
    train_chunk_size: 32_768

  noise_generator_type: "triplane-noise-generator"
  noise_generator:
    # 0(random)-1(determined)
    sqrt_beta: [3_000, 0., 1.0, 3_001]
    noise_h: 64
    noise_w: 64
    noise_background_fix: true

    noise_ptc_resolution: 2048
    peel_depth: 32 # just some large number
    separate: false
    apply_transformation: sph2sqr
    context_type: cuda

    smooth_regularization: true
    weight_decay: 1.0

  t_scheduler_type: timestep-scheduler
  t_scheduler:
    min_step_percent: 0.02
    max_step_percent: 0.98
    sqrt_anneal: false
    dreamtime_anneal: [700,300,100,1]
    trainer_max_steps: ${trainer.max_steps}

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: "A 3D model of an adorable cottage with a thatched roof"
    # negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "stable-diffusion-unified-guidance"
  guidance:
    weighting_strategy: dmd
    guidance_type: vsd
    guidance_stab_type: null
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    vsd_phi_model_name_or_path: "stabilityai/stable-diffusion-2-1"
    guidance_scale: 7.5
    use_img_loss: null

  loggers:
    wandb:
      enable: false
      project: ${name}
      name: ${tag}

  loss:
    lambda_sd: 1.
    lambda_sd_img: 1e-1
    lambda_train_phi: 1.
    lambda_normal_smooth: 0.
    lambda_3d_normal_smooth: 0.
    lambda_orient: 0.
    lambda_sparsity: 10.
    lambda_opaque: 0.
    lambda_z_variance: 0.

  optimizer:
    name: Adam
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.density_network:
        lr: 0.001
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001
      guidance:
        lr: 1e-4

trainer:
  max_steps: 25_000
  log_every_n_steps: 50
  num_sanity_val_steps: 0
  val_check_interval: 500
  enable_progress_bar: true
  precision: bf16

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
